branchName: "chistock-#${issue.number}"
  autoCloseIssue: true
  openDraftPR: true
  copyIssueLabelsToPR: true
  copyIssueAssigneeToPR: true
  branches:
    - label: bug
      prefix: bugfix/
    - label: issue
      prefix: issuefix/
    - label: release
      skip: true
    - label: env
      skip: true
    - label: feature
      prefix: feature/
    - label: duplicate
      skip: true
    - label: sub_issue
      skip: true
    - label: refactor
      prefix: refactor/
    - label: test
      prefix: test/
    - label: docs
      prefix: document/
